### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by heyhippari** [SittingDucksModels/scalemodel-links#2]
It'd be good to have a license, as it's a community project :)

The Awesome Lists project recommends [Creative Commons CC0](https://creativecommons.org/publicdomain/zero/1.0/).  
There's a lot of other alternatives, but it'd be good to have one, so that rights about usage, contribution, modification, redistribution and so on are explicit. 

Ideally, it should be added to the repository in the form of a LICENSE or licence.md file.

**Comment by SittingDucksModels** [comment]
LICENCE added.
